### ISSUE TITLE
adding prettier , eslint

### ISSUE THREAD

**Issue by BuG-Dev-Joris** [WildCodeSchool/lyon-js-react-march21-g1-p2#2]
addding prettier and eslint and some stuff

**Comment by Herelius** [comment]
Can you see if the "init" branche works plz? (EsLint and Prettier)

**Comment by Nels-J** [comment]
@Herelius
 This not seem to meet the requirement from Pierre about the init let review that tomorow together.
Currently the initilization branch feel more clearer and with husky enabled on it.

@DuboisCecile please make a PR to your branch.
